title: Divine Steam 2

nav:
  - Home: index.md
  - Classes: 
        - Magician:
          - Magician: classes/Magician/mage
          - Escapist: classes/Magician/escapist
          - Chirurgy: classes/Magician/chirurgy
