nav:
  - Class home: classes.md
  - Magician:
    - Magician: magician/mage.md
    - Subclasses:
      - Escapist: magician/escapist.md
      - Chirurgy: magician/chirurgy.md
  - DS Reworked Subclasses:
    - Eldritch Knight: subclasses/EldritchKnight.md
    - Arcane Trickster: subclasses/ArcaneTrickster.md